### ISSUE TITLE
Views of root entity do not preserve root's hierarchy

### ISSUE THREAD

**Issue by barsoosayque** [viridia/quill#5]
Spawning root element inside a hierarchy would not spawn its views inside the same hierarchy. 

In my case, I spawn the whole UI inside a _scene root_-entity that I then use to despawn everything recursively when the scene is done.  I can see that there are some elements inside a hierarchy (I assume dynamic ones ?), but the whole UI tree is just spawned at the root of the world. This is a bit problematic, because I rely on the hierarchy quite a lot for my scene management, and as far as I can tell there is no way to make it spawn UI somewhere else ?

_(The library seems very nice, by the way)_

**Comment by viridia** [comment]
Here's what you can do: In your root template, instead of calling `Element::<NodeBundle>::new()`, call `Element::<NodeBundle>::for_entity(entity)`, where `entity` is an entity you have already created that has the proper parent. If your root is a view template, you can pass in the entity as a parameter.

**Comment by barsoosayque** [comment]
Ah, ok, that works, thanks ! Another problem is that bevy's UI kinda doesn't allow that, but that's irrelevant to this issue.
