### ISSUE TITLE
Tracking doesn't account for removal

### ISSUE THREAD

**Issue by barsoosayque** [viridia/quill#6]
If I understand things correctly, both components and resources are tracked only for their change ticks, i.e. begin added and modified. But removal is also a part of change detection, albeit a bit awkward one. It would be nice to check for `world.removed_with_id(component_id)` and see if the tracked component was deleted, I'm not sure what would work for resources, maybe just `world.contains_resource()` ?

**Comment by viridia** [comment]
I ran into this a while back and didn't have a good solution for it at the time. Maybe now with component hooks: basically what we would need is to store an on_remove hook in the tracking scope, and have it set the scope's `changed` field.

The hard part is that scope dependencies must be one-shots: each time a scope triggers an update, all data dependencies are cleared, and then running the reaction rebuilds the dependency map. This is the secret of how reactive systems avoid the need to manually call `unsubscribe()`. This is easy enough to do with components and resources - just empty out the hash maps containing the ids. On_remove hooks, OTH, are persistent, so we'd need to cancel the hook and re-subscribe every update (otherwise we risk leaking hooks, dangling hooks, or worse.)

One could possibly get clever and try to do some sort of "hook garbage collection", that is, keep around the hook and only remove it if not re-subscribed, but this is complex. Alternatively, one could set up a *global* on_remove hook and then try to dispatch it to all tracking scopes, but this will probably perform badly.

**Comment by viridia** [comment]
I also don't handle component additions very well either, currently.

**Comment by viridia** [comment]
Hmmm, for components it might not be that complicated - you don't need a change tick, all you need to know is "does the component still exist?". You also have to remember whether or not the component existed at the time you subscribed to it.

**Comment by viridia** [comment]
That turned out to be easier than I expected: https://github.com/viridia/quill/commit/63bb3ed72cd539c10d88fe265f51cf15cc3b891e

**Comment by barsoosayque** [comment]
Can confirm this works in my case !
